name: Content CI
on:
  pull_request:
    paths:
      - 'content/**.md'
  push:
    branches: [ main ]
    paths:
      - 'content/**.md'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure front-matter exists (title & updated)
        run: |
          set -e
          fail=0
          while IFS= read -r -d '' f; do
            head -n 30 "$f" | grep -q '^---$' || { echo "Missing fm start: $f"; fail=1; continue; }
            head -n 30 "$f" | grep -q '^title:' || { echo "Missing title: $f"; fail=1; }
            head -n 30 "$f" | grep -q '^updated:' || { echo "Missing updated: $f"; fail=1; }
          done < <(find content -name '*.md' -print0)
          [ $fail -eq 0 ]

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            content/**/*.md
