name: Content CI

on:
  pull_request:
    paths:
      - 'content/**/*.md'
      - '.github/workflows/content-ci.yml'
      - '.markdownlint.json'
  push:
    branches: [main]
    paths:
      - 'content/**/*.md'
      - '.github/workflows/content-ci.yml'
      - '.markdownlint.json'

jobs:
  front-matter:
    name: Validate front matter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate front matter
        uses: tj-actions/validate-front-matter@v16
        with:
          files: |
            content/**/*.md

  markdownlint:
    name: Lint Markdown content
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            content/**/*.md
          config: .markdownlint.json
