name: Content CI / lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
      - '.markdownlintignore'
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
      - '.markdownlintignore'

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No network install; uses a prebuilt action container for markdownlint-cli2
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          # Respect repo config and ignore common build dirs
          config: .markdownlint.jsonc
          globs: |
            **/*.md
            !node_modules/**
            !**/dist/**
